version: '3'
services:
  web:
    image: california-app-web:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql://root:example@db:3306/mydatabase
    volumes:
      - logs:/app/logs
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  logs:
  db_data:


